In [49]:
import pandas as pd
import numpy as np
import sklearn
from pandas import DataFrame

In [50]:
FLT_1 = pd.read_excel('FLT 1 Revised.xlsx').drop(columns='t(s)')
x = FLT_1[0:(len(FLT_1)-1)]
y = FLT_1[1:(len(FLT_1))]
len(FLT_1)
FLT_1

,aoa (deg),pitch (deg),pitch speed (deg/s),true speed (m/s),Cd,Cl,Cm
0,1.978644,1.994105,0.009835,50.741865,0.050988,0.460989,0.001941
1,1.978343,1.994686,0.009787,50.742590,0.050972,0.461021,0.001953
2,1.978041,1.995267,0.009738,50.743315,0.050956,0.461052,0.001966
3,1.977740,1.995847,0.009690,50.744040,0.050941,0.461083,0.001978
4,1.977439,1.996428,0.009642,50.744765,0.050925,0.461115,0.001990
...,...,...,...,...,...,...,...
99995,2.391689,2.924688,-0.012253,50.285324,0.043411,0.416994,-0.004519
99996,2.391753,2.924688,-0.012253,50.285324,0.043395,0.416750,-0.004529
99997,2.391817,2.924688,-0.012253,50.285324,0.043379,0.416508,-0.004539
99998,2.391882,2.924688,-0.012253,50.285324,0.043364,0.416266,-0.004549
99999,2.391946,2.924688,-0.012253,50.285324,0.043348,0.416024,-0.004559

In [51]:
from sklearn.model_selection import train_test_split
x_main, x_test, y_main, y_test = train_test_split (x,y, test_size=10000)
x_training, x_validation, y_training, y_validation =train_test_split(x_main,y_main, test_size=10000)
print(x_test.shape)
print(x_validation.shape)
print(x_training.shape)
DataFrame.sort_index(x_test,ignore_index = True)

(10000, 7)
(10000, 7)
(79999, 7)

,aoa (deg),pitch (deg),pitch speed (deg/s),true speed (m/s),Cd,Cl,Cm
0,1.976535,1.998169,0.009497,50.746940,0.050880,0.461209,0.002028
1,1.970226,2.010331,0.008487,50.762131,0.050616,0.461865,0.002287
2,1.968432,2.013790,0.008200,50.766453,0.050555,0.462051,0.002361
3,1.966346,2.017811,0.007865,50.771481,0.050493,0.462267,0.002447
4,1.966049,2.018385,0.007818,50.772198,0.050484,0.462297,0.002459
...,...,...,...,...,...,...,...
9995,2.388870,2.924688,-0.012253,50.285326,0.044211,0.427994,-0.004076
9996,2.390857,2.924688,-0.012253,50.285325,0.043628,0.420186,-0.004388
9997,2.390921,2.924688,-0.012253,50.285325,0.043611,0.419938,-0.004398
9998,2.391177,2.924688,-0.012253,50.285324,0.043543,0.418951,-0.004438
9999,2.391689,2.924688,-0.012253,50.285324,0.043411,0.416994,-0.004519